<header id="gtco-header" class="gtco-cover gtco-cover-md" role="banner" style="background-image: url(/foodanddrink/img/background/anhnen2.jpg)" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="gtco-container">
        <div class="row">
            <div class="col-md-12 col-md-offset-0 text-left">


                <div class="row row-mt-15em">
                    <div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp" style="text-align: center;">
                        <span class="intro-text-small">Creat by <a href="http://gettemplates.co" target="_blank">Food And Drink</a></span>
                        <h1 class="cursive-font">Đậm đà hương vị Việt!</h1>
                    </div>
                    <div class="col-md-4 col-md-push-1 animate-box" data-animate-effect="fadeInRight">
                        <div class="form-wrap">
                            <div class="tab">

                                <div class="tab-content">
                                    <div class="tab-content-inner active" data-content="signup">
                                        <h3 class="cursive-font">Đặt Bàn</h3>
                                        <form method="post">
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="activities">Số lượng người</label>
                                                    <input type="number" min="1" name="soNguoi" value="2" class="form-control">
                                                </div>
                                            </div>
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="date-start">Ngày</label>
                                                    <input type="text" id="date" name="ngay" class="form-control">
                                                </div>
                                            </div>
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="date-start">Giờ</label>
                                                    <input type="text" id="time" name="gio" class="form-control">
                                                </div>
                                            </div>

                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <input type="submit" name="btnDatBan" id="btnDatBan" class="btn btn-primary btn-block" value="Đặt Ngay">
                                                </div>
                                                <div class="col-md-12" style="margin-top: 10px;">
                                                    <?php
                                                    if (isset($ketQua)){

                                                        echo '<i style="color: rgb(255, 85, 0);">*'.$ketQua.'</i>';
                                                        echo '<br>';
                                                    }
                                                    ?>
                                                </div>
                                            </div>
                                        </form>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</header>

<div class="hidden">
    <p class="username"><?php echo $this->cookies->get('username');?></p>
</div>
<?php $this->assets->outputJs(); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/jquery-3.4.1.min.js"); ?>
<script>
    $(document).ready(function () {
        var socket = io("http://localhost:3000");
        $("#btnDatBan").click(function () {
            var username =$(".username").html();
            socket.emit("dat-ban",username);
        })
    });
</script>
