<div class="row">
    <?php
    for($i=0;$i<18;$i++){
        echo '
                        <div class="col-lg-4 col-md-4 col-sm-6">
                            <a href="/foodanddrink/files/anhsp/'.$data[$i]['hinhAnh'].'" class="fh5co-card-item">
                                <figure>
                                    <div class="overlay"><i class="ti-plus"></i></div>
            
                                    <img src="/foodanddrink/files/anhsp/'.$data[$i]['hinhAnh'].'" alt="Image" class="img-responsive">
                                </figure>
                                <div class="fh5co-text">
                                    <h2>Cà Phê Capuchino</h2>
                                    <p style="color: orange"><span class="price cursive-font">'.$data[$i]['gia'].'</span> .đ</p>
                                </div>
                            </a>
                            <input type="button" class="btnmua" name="" value="Mua" onclick="addsp()">
                        </div>
                    ';
    }
    ?>
</div>
<div class="stuffpost_paginatinonarea wow slideInLeft">
    <ul class="newstuff_pagnav">
        <?php
        if ($page <=3) {
            echo '<li><a href="http://localhost/foodanddrink/menu">1</a></li>';
            for ($i = 2; $i <= 5; $i++) {
                if ($i == $page) {
                    echo '
                        <li><a class="active_page" href="http://localhost/foodanddrink/menu/page?id=' . $i . '">' . $i . '</a></li>
                    ';
                } else {
                    echo '<li><a href="http://localhost/foodanddrink/menu/page?id=' . $i . '">' . $i . '</a></li>';
                }
            }
        }else{
            for ($i=$page-2;$i<=$page+2;$i++){
                if ($i == $page) {
                    echo '
                        <li><a class="active_page" href="http://localhost/foodanddrink/menu/page?id=' . $i . '">' . $i . '</a></li>
                    ';
                } else {
                    echo '<li><a href="http://localhost/foodanddrink/menu/page?id=' . $i . '">' . $i . '</a></li>';
                }
            }
        }
        ?>
    </ul>
</div>