<header id="gtco-header" class="gtco-cover gtco-cover-md" role="banner" style="background-image: url(/foodanddrink/img/background/anhnen2.jpg)" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="gtco-container">
        <div class="row">
            <div class="col-md-12 col-md-offset-0 text-left">


                <div class="row row-mt-15em">
                    <form method="post" enctype="multipart/form-data">
                        <div class="updateUser" data-animate-effect="fadeInRight">
                            <div class="form-wrap">
                                <div class="tab">
                                    <div class="tab-content">
                                        <div class="tab-content-inner active" data-content="signup">
                                            <h3 class="cursive-font" style="font-family:arial;text-align: center;font-style: bold;">Chỉnh sửa thông tin sản phẩm có mã: <b><?php echo $data['maSP']; ?></b></h3>
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="date-start">Tên sản phẩm</label>
                                                    <input type="text" name="txtTenSP" value="<?php echo $data['tenSP']; ?>"  class="form-control" >
                                                </div>
                                            </div>
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="activities">Loại sản phẩm</label>
                                                    <input type="text" name="txtLoaiSP" value="<?php echo $data['loai']; ?>" class="form-control">
                                                </div>
                                            </div>
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="activities">Mô tả:</label>
                                                    <input type="text"  name="txtMoTa" value="<?php echo $data['moTa']; ?>" class="form-control">
                                                </div>
                                            </div>
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="activities">Giá:</label>
                                                    <input type="text"  name="txtGiaSP" value="<?php echo $data['gia']; ?>" class="form-control">
                                                </div>
                                            </div>
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="date-start">Hình sản phẩm (dưới 5MB)</label>
                                                    <img class="imgEdit" src="/foodanddrink/files/anhsp/<?php echo $data['hinhAnh']?>">
                                                    <input type="file" name="fileHinhSP">
                                                </div>
                                            </div>
                                            <div id="kqktUser" style="color: rgb(255, 85, 0);"></div>
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <input type="submit" id="btnSubmit" name="editSP" class="btn btn-primary btn-block" value="Lưu thông tin">
                                                </div>
                                                <div class="col-md-12" style="margin-top: 10px;">
                                                    <?php
                                                    if (isset($ketQua)){

                                                        echo '<i style="color: rgb(255, 85, 0);">*'.$ketQua.'</i>';
                                                        echo '<br>';
                                                    }

                                                    ?>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>

                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</header>
<style>
    .updateUser{
        margin-top: -120px;
    }
    .imgEdit{
        width: 100px;
    }
</style>