<header id="gtco-header" class="gtco-cover gtco-cover-md" role="banner" style="background-image: url(img/background/anhnen2.jpg)" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="gtco-container">
        <div class="row">
            <div class="col-md-12 col-md-offset-0 text-left">


                <div class="row row-mt-15em">
                    <div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp" style="text-align: center;">
                        <span class="intro-text-small">Creat by <a href="http://gettemplates.co" target="_blank">Food And Drink</a></span>
                        <h1 class="cursive-font">Đậm đà hương vị Việt!</h1>
                    </div>
                    <div class="col-md-4 col-md-push-1 animate-box" data-animate-effect="fadeInRight">
                        <div class="form-wrap">
                            <div class="tab">

                                <div class="tab-content">
                                    <div class="tab-content-inner active" data-content="signup">
                                        <h3 class="cursive-font">Đặt Bàn</h3>
                                        <form action="#">
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="activities">Số lượng người</label>
                                                    <input type="number" min="1" name="" value="1" class="form-control">
                                                </div>
                                            </div>
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="date-start">Ngày</label>
                                                    <input type="text" id="date" class="form-control">
                                                </div>
                                            </div>
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="date-start">Giờ</label>
                                                    <input type="text" id="time" class="form-control">
                                                </div>
                                            </div>

                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <input type="submit" class="btn btn-primary btn-block" value="Đặt Ngay">
                                                </div>
                                            </div>
                                        </form>
                                    </div>


                                </div>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</header>



<!--<div class="gtco-section">-->
<!--    <div class="gtco-container">-->
<!--        <div class="row">-->
<!--            <div class="col-md-8 col-md-offset-2 text-center gtco-heading">-->
<!--                <h2 class="cursive-font primary-color">Best Seller</h2>-->
<!--                <p>Mua thì mua không mua thì cút!</p>-->
<!--            </div>-->
<!--        </div>-->
<!---->
<!--        <div class="row">-->
<!--            --><?php
//            for($i=0;$i<18;$i++){
//                echo '
//                        <div class="col-lg-4 col-md-4 col-sm-6">
//                            <a href="files/anhsp/'.$data[$i]['hinhAnh'].'" class="fh5co-card-item">
//                                <!-- <a href="anh/drink/cafe/capuchino.jpg" class="fh5co-card-item image-popup"> -->
//                                <figure>
//                                    <div class="overlay"><i class="ti-plus"></i></div>
//
//                                    <img src="files/anhsp/'.$data[$i]['hinhAnh'].'" alt="Image" class="img-responsive">
//                                </figure>
//                                <div class="fh5co-text">
//                                    <h2>Cà Phê Capuchino</h2>
//                                    <input type="hidden" value="'.$data[$i]['maSP'].'">
//                                    <p style="color: orange"><span class="price cursive-font">'.$data[$i]['gia'].'</span> .đ</p>
//                                </div>
//                            </a>
//                            <input type="button" class="btnmua" name="" value="Mua"">
//                        </div>
//                    ';
//            }
//            ?>
<!--        </div>-->
<!--        <div class="stuffpost_paginatinonarea wow slideInLeft">-->
<!--            <ul class="newstuff_pagnav">-->
<!--                <li><a class="active_page" href="#">1</a></li>-->
<!--                <li><a href="http://localhost/foodanddrink/menu/page?page=2">2</a></li>-->
<!--                <li><a href="http://localhost/foodanddrink/menu/page?page=3">3</a></li>-->
<!--                <li><a href="http://localhost/foodanddrink/menu/page?page=4">4</a></li>-->
<!--                <li><a href="http://localhost/foodanddrink/menu/page?page=5">5</a></li>-->
<!--            </ul>-->
<!--        </div>-->
    </div>
</div>
