<header id="gtco-header" class="gtco-cover gtco-cover-md" role="banner" style="background-image: url(/foodanddrink/img/background/anhnen2.jpg)" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="gtco-container">
        <div class="row">
            <div class="col-md-12 col-md-offset-0 text-left">


                <div class="row row-mt-15em">
                    <div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp" style="text-align: center;">
                        <span class="intro-text-small">Creat by <a href="http://gettemplates.co" target="_blank">Food And Drink</a></span>
                        <h1 class="cursive-font">Đậm đà hương vị Việt!</h1>
                    </div>
                    <div class="col-md-4 col-md-push-1 animate-box" data-animate-effect="fadeInRight">
                        <div class="form-wrap">
                            <div class="tab">

                                <div class="tab-content">
                                    <div class="tab-content-inner active" data-content="signup">
                                        <h3 class="cursive-font" style="font-family:arial;text-align: center;font-style: bold;">Đổi mật khẩu</h3>
                                        <form method="post">
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="activities">Mật khẩu cũ</label>
                                                    <input type="password" name="passwordCu" id="txtPasswordCu" placeholder="********" class="form-control">
                                                </div>
                                            </div>
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="date-start">Mật khẩu mới</label>
                                                    <input type="password" name="passwordMoi" id="txtPasswordMoi" placeholder="********" class="form-control" placeholder="">
                                                </div>
                                            </div>
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <label for="date-start">Nhập lại mật khẩu mới</label>
                                                    <input type="password" name="passwordMoi2" id="txtPasswordMoi2" placeholder="********" class="form-control" placeholder="">
                                                </div>
                                            </div>
                                            <div id="ketQuaKT" style="color: rgb(255, 85, 0);"></div>
                                            <div class="row form-group">
                                                <div class="col-md-12">
                                                    <input type="submit" id="btnSubmit" name="btnSubmit" class="btn btn-primary btn-block" value="Đổi mật khẩu">
                                                </div>
                                                <?php
                                                if (isset($ketQua)){

                                                    echo '<i style="color: rgb(255, 85, 0);">'.$ketQua.'</i>';
                                                    echo '<br>';
                                                }

                                                ?>
                                                <div class="col-md-12" style="margin-top: 10px;">
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<?php echo \Phalcon\Tag::javascriptInclude("js/jquery-3.4.1.min.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/kiemtradoimatkhau.js"); ?>


<?php
//    echo $_COOKIE['username'];
//?>
<!--<div>-->
<!--    <form method="post">-->
<!--        <table>-->
<!--            <tr>-->
<!--                <td>Mật khẩu cũ:</td>-->
<!--                <td><input type="text" name="passwordCu" id="txtPasswordCu"></td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--                <td>Mật khẩu mới:</td>-->
<!--                <td><input type="text" name="passwordMoi" id="txtPasswordMoi"></td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--                <td>Nhập lại Mật khẩu mới:</td>-->
<!--                <td><input type="text" name="passwordMoi2" id="txtPasswordMoi2"></td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--                <td colspan="2">-->
<!--                    <input type="submit" id="btnSubmit" name="btnSubmit" value="Đổi mật khẩu">-->
<!--                </td>-->
<!--            </tr>-->
<!--        </table>-->
<!--    </form>-->
<!--    <div id="ketQuaKT"></div>-->
<!--</div>-->

<?php
//    if (isset($kq)){
//        echo $kq;
//    }
//?>
