<?php $this->assets->outputCss(); ?>
<form>
    <header id="gtco-header" class="gtco-cover gtco-cover-md" role="banner" style="background-image: url(/foodanddrink/img/background/anhnen2.jpg)" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="gtco-container">
            <div class="row">
                <div class="col-md-12 col-md-offset-0 text-left">
                    <div class="donHang">
                        <div class="menuDonHang">
                            <ul>
                                <li><a href="http://localhost/foodanddrink/users/datban?tt=all&page=1">Tất cả</a></li>
                                <li><a href="http://localhost/foodanddrink/users/datban?tt=cho&page=1">Chờ xác nhận</a></li>
                                <li><a href="http://localhost/foodanddrink/users/datban?tt=datThanhCong&page=1">Đặt thành công</a></li>
                                <li><a href="http://localhost/foodanddrink/users/datban?tt=daNhanBan&page=1">Đã nhận bàn</a></li>
                                <li><a href="http://localhost/foodanddrink/users/datban?tt=daHuy&page=1">Đã hủy<a/></li>
                            </ul>
                        </div>
                        <div class="noiDungDonHang">
                            <table class="bangTT">
                                <tr>
                                    <th>Mã đặt bàn</th>
                                    <th>Số lượng người</th>
                                    <th>Thời gian</th>
                                    <th>Trạng thái</th>
                                    <th>Thao tác</th>
                                </tr>
                                <?php
                                $i=0;
                                foreach ($data as $x){
                                    echo '
                                        <tr>
                                            <td>'.$x['maDatBan'].'</td>
                                            <td>'.$x['soNguoi'].'</td>
                                            <td >'.$x['thoiGian'].'</td>
                                            <td>'.$x['trangThai'].'</td>';
                                    if ($x['trangThai'] =="datThanhCong"){
                                        echo '
                                            <td><a class="btnTT" href="http://localhost/foodanddrink/datban/chuyenTT?maDatBan='.$x['maDatBan'].'&tt=daNhanBan">Đã nhận bàn</a></td>
                                         </tr>
                                        ';

                                    }else{
                                        if ($x['trangThai'] =="cho"){
                                            echo '
                                            <td><a class="btnTT" href="http://localhost/foodanddrink/datban/chuyenTT?maDatBan='.$x['maDatBan'].'&tt=daHuy">Hủy</a></td>
                                         </tr>
                                        ';

                                        }else{
                                            echo '
                                                <td>Xong</td>
                                             </tr>
                                            ';
                                        }
                                    }
                                }
                                ?>
                            </table>
                            <div>
                                <ul class="ulPhanTrang">
                                    <?php
                                    for ($i=1;$i<=10;$i++){
                                        if ($i == $page){
                                            echo '
                                                <li><a class="active_page" href="http://localhost/foodanddrink/users/datban?tt='.$tt.'&page='.$i.'">'.$i.'</a></li>
                                            ';
                                        }else{
                                            echo '
                                                <li><a href="http://localhost/foodanddrink/users/datban?tt='.$tt.'&page='.$i.'">'.$i.'</a></li>
                                            ';
                                        }
                                    }
                                    ?>

                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
</form>
<style>
    .donHang{
        margin-top: 150px;
        height: auto;
        background: white;
    }
    .menuDonHang{
        text-align: center;
        background: #352823;
        height: 50px;
    }
    .menuDonHang ul li{
        display: inline-table;
        width: 120px;
        line-height: 50px;
        height: 50px;
    }
    .menuDonHang ul li a{
        display: block;
    }
    .menuDonHang ul li:hover{
        background-color: #5cb85c;
    }
    .noiDungDonHang{
        color: black !important;
        padding-bottom: 50px;
    }
    .listSP a{
        color: #ea1a1a !important;
    }
    .bangTT{
        color: black!important;
        width: 100%;
        margin-bottom: 50px;
    }
    .bangTT th{
        border-bottom: 1px solid #3b5059;
        padding: 5px;
    }
    .bangTT td{
        height: 35px;
    }
    .bangTT td a{
        border: 2px solid white;
    }
    .btnTT{
        background: #4d4d4d;
        width: 5px;
        padding: 5px;
    }
    .bangTT td a:hover{
        background: #ec971f;
    }
    .ulPhanTrang li{
        width: 30px;
        list-style-type: none;
        color:black !important;
        display: inline-table;
        background: #4d4d4d;
        text-align: center;
    }
    .ulPhanTrang li:hover{
        background: wheat;
    }
    .active_page{
        color: black!important;
    }
</style>