<div>
    <form method="post">
        <table>
            <tr>
                <td>Username:</td>
                <td><input type="text" name="username" id="txtUsername"></td>
            </tr>
            <tr>
                <td>Password:</td>
                <td><input type="text" name="password" id="txtPassword"></td>
            </tr>
            <tr>
                <td colspan="2">
                    <input type="submit" id="btnSubmit" name="btnSubmit" value="Đăng nhập">
                </td>
            </tr>
        </table>
    </form>
</div>
<?php
//    echo $kq;
    echo "----------username:".$this->cookies->get('username');
?>
