
<header id="gtco-header" class="gtco-cover gtco-cover-md" role="banner" style="background-image: url(/foodanddrink/img/background/anhnen2.jpg)" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="gtco-container">
        <div class="row">
            <div class="col-md-12 col-md-offset-0 text-left">


                <div class="row row-mt-15em">
                    <form method="post">
                        <div class="updateUser" data-animate-effect="fadeInRight">
                            <div class="form-wrap">
                                <div class="tab">
                                    <div class="tab-content">
                                        <div class="tab-content-inner active" data-content="signup">
                                            <h3 class="cursive-font" style="font-family:arial;text-align: center;font-style: bold;">Cập nhật thông tin tài khoản</h3>

                                                <div class="row form-group">
                                                    <div class="col-md-12">
                                                        <label for="activities">Họ Tên</label>
                                                        <input type="text" name="hoTen" value="<?php echo $data['hoTen']?>" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="row form-group">
                                                    <div class="col-md-12">
                                                        <label for="date-start">Số điện thoại</label>
                                                        <input type="text" name="sdt"  class="form-control" value="<?php echo $data['sdt']?>">
                                                    </div>
                                                </div>
                                                <div class="row form-group">
                                                    <div class="col-md-12">
                                                        <label for="activities">Email</label>
                                                        <input type="text" name="email" value="<?php echo $data['email']?>" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="row form-group">
                                                    <div class="col-md-12">
                                                        <label for="activities">Giới tính</label>
                                                        <input type="text" name="gioiTinh" value="<?php echo $data['gioiTinh']?>" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="row form-group">
                                                    <div class="col-md-12">
                                                        <label for="activities">Năm sinh</label>
                                                        <input type="text" name="namSinh" value="<?php echo $data['namSinh']?>" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="row form-group">
                                                    <div class="col-md-12">
                                                        <label for="activities">Địa chỉ</label>
                                                        <input type="text" name="diaChi" value="<?php echo $data['diaChi']?>" class="form-control">
                                                    </div>
                                                </div>
                                                <div class="row form-group">
                                                    <div class="col-md-12">
                                                        <input type="submit" name="btnSubmit" class="btn btn-primary btn-block" value="Cập nhật thông tin">
                                                    </div>
                                                    <div class="col-md-12" style="margin-top: 10px;">
                                                        <?php
                                                        if (isset($ketQua)){

                                                            echo '<i style="color: rgb(255, 85, 0);">*'.$ketQua.'</i>';
                                                            echo '<br>';
                                                        }

                                                        ?>
                                                    </div>
                                                </div>
                                        </div>

                                    </div>
                                </div>
                            </div>

                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</header>
<style>
    .updateUser{
        margin-top: -120px;
    }
</style>
<!--<form method="post">-->
<!--    <table>-->
<!--        <tr>-->
<!--            <td>Họ tên:</td>-->
<!--            <td><input type="text" name="hoTen" id="txtHoTen" value="--><?php //echo $data['hoTen']?><!--"></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <td>Số điện thoại:</td>-->
<!--            <td><input type="text" name="sdt" id="txtSdt" value="--><?php //echo $data['sdt']?><!--"></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <td>Email:</td>-->
<!--            <td><input type="text" name="email" id="txtEmail" value="--><?php //echo $data['email']?><!--"></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <td>Giới tính:</td>-->
<!--            <td><input type="text" name="gioiTinh" id="txtGioiTinh" value="--><?php //echo $data['gioiTinh']?><!--"></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <td>Năm sinh:</td>-->
<!--            <td><input type="text" name="namSinh" id="txtNamSinh" value="--><?php //echo $data['namSinh']?><!--"></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <td>Địa chỉ:</td>-->
<!--            <td><input type="text" name="diaChi" id="txtDiaChi" value="--><?php //echo $data['diaChi']?><!--"></td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <td colspan="2">-->
<!--                <input type="submit" id="btnSubmit" name="btnSubmit" value="Lưu thông tin">-->
<!--            </td>-->
<!--        </tr>-->
<!--    </table>-->
<!--</form>-->
<?php
//    if (isset($kq)){
//        var_dump($kq);
//    }
//?>