
<header id="gtco-header" class="gtco-cover gtco-cover-md" role="banner" style="background-image: url(images/img_bg_1.jpg)" data-stellar-background-ratio="0.5">
</header>
<div>
    <form method="post" enctype="multipart/form-data">
        <table>
            <tr>
                <th>Ma SP</th>
                <td>
                    <input type="text" name="txtMaSP" >
                </td>
            </tr>
            <tr>
                <th>Ten SP</th>
                <td>
                    <input type="text" name="txtTenSP" >
                </td>
            </tr>
            <tr>
                <th>Loai SP</th>
                <td>
                    <input type="text" name="txtLoaiSP" >
                </td>
            </tr>
            <tr>
                <th>Mota SP</th>
                <td>
                    <input type="text" name="txtMoTa" >
                </td>
            </tr>
            <tr>
                <th>Gia SP</th>
                <td>
                    <input type="text" name="txtGiaSP" >
                </td>
            </tr>
            <tr>
                <th>Hinh SP</th>
                <td>
                    <input type="file" name="fileHinhSP" >
                </td>
            </tr>
        </table>
        <input type="submit" name="themSP" value="Thêm">
    </form>
</div>
<?php
//if (isset($_POST['themSP'])){
//    var_dump($kq);
//}
//?>
