<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner" style="background-image: url(/foodanddrink/img/background/anhnen2.jpg)">
    <div class="overlay"></div>
    <div class="gtco-container">
        <div class="row">
            <div class="col-md-12 col-md-offset-0 text-center">
                <div class="row row-mt-15em">
                    <div class="col-md-7 mt-text animate-box" data-animate-effect="fadeInUp" style="margin-top:-50px; ">
                        <span class="intro-text-small">Creat by <a href="http://gettemplates.co" target="_blank">Food And Drink</a></span>
                        <h1 class="cursive-font">Đậm đà hương vị Việt!</h1>
                    </div>
                </div>

            </div>
        </div>
    </div>
</header>

<div class="gtco-section">
    <div class="gtco-container">
        <div class="row">
            <div class="col-md-12">
                <div class="col-md-6 animate-box">
                    <!-- <h3></h3> -->
                    <form action="https://formspree.io/foodanddrink.hotro@gmail.com" method="post">
                        <div class="row form-group">
                            <div class="col-md-12">
                                <label class="sr-only" for="name">Name</label>
                                <input type="text" id="name" name="Name" class="form-control" placeholder="Tên">
                            </div>

                        </div>

                        <div class="row form-group">
                            <div class="col-md-12">
                                <label class="sr-only"  for="email">Email</label>
                                <input type="text" id="email" name="Email" class="form-control" placeholder="Email">
                            </div>
                        </div>
                        <div class="row form-group">
                            <div class="col-md-12">
                                <label class="sr-only"  for="message">Message</label>
                                <textarea name="message" id="message" cols="30" rows="10" class="form-control" placeholder="Nội dung"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Gửi" class="btn btn-primary">
                        </div>

                    </form>
                </div>
                <div class="col-md-5 col-md-push-1 animate-box">
                    <div class="gtco-contact-info">
                        <h3>Thông Tin Liên Hệ</h3>
                        <ul>
                            <li class="address">Cửa Hàng Food And Drink, Đường Z115, Tp.Thái Nguyên<br> </li>
                            <li class="phone"><a href="tel://0399999999">+ 0399999999</a></li>
                            <li class="email"><a href="mailto:foodanddrink@gmail.com">foodanddrink.hotro@gmail.com</a></li>
                            <li class="url"><a href="http://foodanddrink.com">foodanddrink.com</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>