<?php
class AdminController extends ControllerBase{
    public function onConstruct()
    {
        parent::onConstruct(); // TODO: Change the autogenerated stub
        $this->view->setRenderLevel(4);
        $headerCollection = $this->assets->collection('header');
        $headerCollection->addCss('css/admin.css');
        $this->assets->addJs('http://localhost:3000/socket.io/socket.io.js', false);
    }

    public function indexAction(){

    }
    public function addSPAction(){
        if (isset($_POST['themSP'])){
            $post = $this->request->getPost();

            $this->view->setVar("post",$post);
            $this->view->setVar("anh",$_FILES['fileHinhSP']);
            $name= $_FILES['fileHinhSP']["name"];
            var_dump($_FILES['fileHinhSP']);
            move_uploaded_file(
                $_FILES['fileHinhSP']['tmp_name'],
                "files/anhsp/$name"
            );
            $data = array(
                'maSP'=> $post['txtMaSP'],
                'tenSP'=> $post['txtTenSP'],
                'loai'=> $post['txtLoaiSP'],
                'hinhAnh'=>$name,
                'moTa'=> $post['txtMoTa'],
                'gia'=>(int)$post['txtGiaSP']
            );
            if($data['maSP'] == "" || $data['tenSP'] == "" || $data['gia'] <= 0){
                $this->view->setVar('ketQua',"Thất bại! Các trường bắt buộc: Mã SP, tên SP, giá.");
                return 1;
            }
            $sanPham = new Sanpham();
            if ($sanPham->save($data)){
                $this->view->setVar('ketQua',"Thêm sản phẩm thành công");
            }else{
                $this->view->setVar('ketQua',"Thêm sản phẩm thất bại");
            }
        }
    }
    public function showSPAction(){
        $start=0;
        if (isset($_GET['id']) && $_GET['id']>1){
            $page= $_GET['id'];
            $start= ($page-1)*20;
            $this->view->setVar('page',$page);
        }
        $data = Sanpham::find([
            'offset'=>$start,
            'limit' => 20,
        ])->toArray();
        $this->view->setVar("data",$data);
    }
    public function donHangAction(){
        $trangThai=$_GET['tt'];
        $page = $_GET['page'];
        $start = ($page-1)*20;
        if ($trangThai == "all"){
            $data = Donhang::find([
                'offset' => $start,
                'order' => 'ngayGiao DESC',
                'limit'=>20
            ])->toArray();
        }else{
            $data = Donhang::find([
                "trangThai='$trangThai'",
                'offset' => $start,
                'order' => 'ngayGiao DESC',
                'limit'=>20
            ])->toArray();
        }
        $this->view->setVar("data",$data);
        $listSanPham=array();
        $i=0;
        foreach ($data as $x){
            $maDonHang = $x['maDonHang'];
            $listSanPham[$i]= Chitietdonhang::find("maDonHang='$maDonHang'")->toArray();
            $i++;
        }
        $this->cookies->set(
            'sltb',
            0,
            time() +43200
        );
        $this->view->setVar("listSanPham",$listSanPham);
        $this->view->setVar("tt",$trangThai);
        $this->view->setVar("page",$page);
    }
    public function tangsltbAction(){
        $this->view->setRenderLevel(2);
        $slTang =1;
        $sltb=0;
        if ($this->cookies->has('sltb')){
            $cookie = (int)$this->cookies->get('sltb')->getValue();
            $sltb = $cookie+(int)$slTang;
        }else{
            $sltb= $slTang;
        }
        $this->cookies->set(
            'sltb',
            $sltb,
            time() +43200
        );
        echo $sltb;
    }
    public function chitietdonhangAction(){
        $maDonHang = $_GET['maDonHang'];
        $data = Chitietdonhang::find("maDonHang = '$maDonHang'")->toArray();
        $this->view->setVar("data",$data);

        $temp = Donhang::findFirst("maDonHang='$maDonHang'")->toArray();
        $username = $temp['username'];
        $dataUser= Users::findFirst("username='$username'")->toArray();
        $ttNguoiNhan = array(
            'hoTen'=> $dataUser['hoTen'],
            'sdt'=>$dataUser['sdt'],
            'diaChi'=>$temp['diaChi'],
        );
        $this->view->setVar("ttNguoiNhan",$ttNguoiNhan);
    }
    public function thongbaoAction(){
        $this->view->setRenderLevel(2);
        $data = Donhang::find([
            "trangThai='cho'",
            'order' => 'ngayGiao DESC',
            'limit' => 15,
        ])->toArray();
        $data1 = Datban::find([
            "trangThai='cho'",
            'order' => 'thoiGian',
            'limit' => 15,
        ])->toArray();
        $this->view->setVar("data",$data);
        $this->view->setVar("data1",$data1);
    }
    public function editSPAction(){
        $maSP  = $_GET['maSP'];
        $data = Sanpham::findFirst("maSP='$maSP'")->toArray();
        $this->view->setVar("data",$data);
        if (isset($_POST['editSP'])){
            $post = $this->request->getPost();
            $name= $_FILES['fileHinhSP']["name"];
            if (strlen($name)>0){
                $nameIMG = $name;
            }else{
                $nameIMG = $data['hinhAnh'];
            }
            $this->view->setVar('anh',$_FILES['fileHinhSP'] ["error"]);
            $dataNew = array(
                'maSP'=> $data['maSP'],
                'tenSP'=> $post['txtTenSP'],
                'loai'=> $post['txtLoaiSP'],
                'hinhAnh'=>$nameIMG,
                'moTa'=> $post['txtMoTa'],
                'gia'=>(int)$post['txtGiaSP']
            );
            if($dataNew['maSP'] == "" || $dataNew['tenSP'] == "" || $dataNew['gia'] <= 0){
                $this->view->setVar('ketQua',"Thất bại! Các trường bắt buộc: Tên SP, giá.");
                return 1;
            }
            $sanPham = new Sanpham();
            if ($sanPham->save($dataNew)){
                move_uploaded_file(
                    $_FILES['fileHinhSP']['tmp_name'],
                    "files/anhsp/$nameIMG"
                );
                $this->view->setVar('ketQua',"Cập nhật thông tin thành công");
            }else{
                $this->view->setVar('ketQua',"Có lỗi sảy ra");
            }
        }
    }
    public function deleteSPAction(){
        $this->view->setRenderLevel(2);
        $maSP=$_GET['maSP'];
        $data=Sanpham::findFirst("maSP='$maSP'");
        if ($data->delete()){
            header('location: http://localhost/foodanddrink/admin/showSP?id=1');
        }else{
            echo "Có lỗi xảy ra!";
        }
    }
    public function datbanAction(){
        $trangThai=$_GET['tt'];
        $page = $_GET['page'];
        $start = ($page-1)*20;
        if ($trangThai == "all"){
            $data = Datban::find([
                'offset' => $start,
                'order' => 'thoiGian DESC',
                'limit'=>20
            ])->toArray();
        }else{
            $data = Datban::find([
                "trangThai='$trangThai'",
                'offset' => $start,
                'order' => 'thoiGian DESC',
                'limit'=>20
            ])->toArray();
        }
        $this->view->setVar("data",$data);
        $this->cookies->set(
            'sltb',
            0,
            time() +43200
        );
        $this->view->setVar("tt",$trangThai);
        $this->view->setVar("page",$page);

        $thongKe =$this->thongKeBan();
        $this->view->setVar("thongke",$thongKe);

        $this->view->setVar("now",date('Y-m-d H:i:s'));

    }
    public function kiemTraMaSPAction(){
        $this->view->disable();
        $post= $this->request->getPost();
        $maSP = $post['maSP'];
        if (Sanpham::findFirst("maSP='$maSP'")){
            echo "*Mã sản phẩm đã tồn tại!";
        }else{
            echo "";
        }

    }
    public function thongKeBan(){
        date_default_timezone_set('Asia/Ho_Chi_Minh');
        $now=getdate();
        $timeInt =$now[0];
        $timeMin = date('Y-m-d H:i:s',$timeInt-3600);
        $timeMax = date('Y-m-d H:i:s',$timeInt+3600);
        $data = Datban::find("thoiGian > '$timeMin' AND thoiGian <'$timeMax' AND (trangThai='datThanhCong' OR trangThai='daNhanBan')")->toArray();
        $data1 = Datban::find("thoiGian > '$timeMin' AND thoiGian <'$timeMax' AND trangThai='daNhanBan'")->toArray();
        $soBanDaDat=0;
        foreach ($data as $x){
            if ($x['soNguoi']<=4){
                $soBanDaDat++;
            }else{
                if ($x['soNguoi']%4 ==0){
                    $soBanDaDat =(int)($soBanDaDat+$x['soNguoi']/4);
                }else{
                    $soBanDaDat =(int)($soBanDaDat+$x['soNguoi']/4+1);
                }
            }
        }
        $soBanDatDaDen=0;
        foreach ($data1 as $x){
            if ($x['soNguoi']<=4){
                $soBanDatDaDen++;
            }else{
                if ($x['soNguoi']%4 ==0){
                    $soBanDatDaDen = (int)($soBanDatDaDen+$x['soNguoi']/4);
                }else{
                    $soBanDatDaDen = (int)($soBanDatDaDen+$x['soNguoi']/4+1);
                }
            }
        }
        $ketQua = array(
            'daDat'=>$soBanDaDat,
            'daDen'=>$soBanDatDaDen
        );
        return $ketQua;
    }
}