<?php $this->assets->outputCss(); ?>
<form action="http://localhost/foodanddrink/users/muaHang" method="post">
    <header id="gtco-header" class="gtco-cover gtco-cover-md" role="banner" style="background-image: url(/foodanddrink/img/background/anhnen2.jpg)" data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="gtco-container">
            <div class="row">
                <div class="col-md-12 col-md-offset-0 text-left">
                    <div class="donHang">
                        <table class="ctdh">
                            <tr>
                                <th>Tên mặt hàng</th>
                                <th>Số lượng</th>
                                <th>Đơn giá</th>
                                <th>Thành tiền</th>
                            </tr>
                            <?php
                            $tong=0;
                            foreach ($data as $x){
                                echo '
                                    <tr>
                                        <td>'.$x['tenSP'].'</td>
                                        <td>'.$x['soLuong'].'</td>
                                        <td>'.$x['gia'].'</td>
                                        <td>'.$x['soLuong']*$x['gia'].'</td>
                                    </tr>
                                ';
                                $tong= $tong+$x['soLuong']*$x['gia'];
                            }
                            echo '
                                <tr class="tong">
                                    <td colspan="2">Tổng:</td>
                                    <td colspan="2">'.$tong.'</td>
                                </tr>
                            ';
                            ?>
                        </table>
                        <table class="tbDiaChi">
                            <tr>
                                <td colspan="2" class="title"><b>Chọn địa chỉ</b></td>
                            </tr>
                            <tr>
                                <td>Địa chỉ mặc định:</td>
                                <td><?php
                                    if (strlen($dataUser['diaChi'])<=0){
                                        echo '<i>*Bạn chưa có địa chỉ mặc định <a href="http://localhost/foodanddrink/users/update">cập nhật</a> ngay</i>';
                                    }else{
                                        echo $dataUser['diaChi']." (Hoặc <a href='http://localhost/foodanddrink/users/update' >cập nhật</a> địa chỉ mới.)";
                                    }
                                    ?></td>
                            </tr>
                            <tr>
                                <td>Hoặc địa chỉ mới:</td>
                                <td><input type="text" class="txtDiaChi" name="diaChi"></td>
                            </tr>
                            <tr>
                                <td colspan="2" class="cmt">*Bỏ trống ô địa chỉ mới để sử dụng địa chỉ mặc định.</td>
                            </tr>
                            <tr>
                                <td></td>
                                <td class="tdDatHang"><input class="btnmuahang" type="submit" value="Đặt Hàng"></td>
                            </tr>
                        </table>
                        <div class="thongBao"><?php if (isset($thongBao)) echo $thongBao ?></div>
                    </div>
                </div>
            </div>
        </div>
    </header>
</form>
<div class="hidden">
    <p class="username"><?php echo $this->cookies->get('username');?></p>
</div>
<?php $this->assets->outputJs(); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/jquery-3.4.1.min.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/muahang.js"); ?>
<style>
    .donHang{
        margin-top: 150px;
        height: auto;
        background: white;
    }
    .ctdh{
        width: 100%;
        color: black;
        border: 1px solid #4cae4c;
    }
    .ctdh td{
        padding: 5px;
    }
    .ctdh th{
        text-align: center;
        background: #31b0d5;
    }
    .tong{
        font-weight: bold;
        text-align: center;
    }
    .tbDiaChi{
        width: 100%;
        border: 1px solid #4cae4c;
        margin-top: 50px;
        color: black;
    }
    .tbDiaChi .title{
        text-align: center;
        background: #31b0d5;
    }
    .tbDiaChi .cmt{
        color: red;
    }
    .tbDiaChi td{
        padding: 5px;
    }
    .tbDiaChi td .txtDiaChi{
        width: 100%;
        border-radius: 5px;
    }
    .tbDiaChi a{
        color: #4cae4c!important;
    }
    .tbDiaChi a:hover{
        background: yellow;
    }
    .tdDatHang{
        text-align: right;
    }
    .btnmuahang{
        margin-right: 50px;
        background: #4cae4c;
        border-radius: 5px;
        font-weight: bold;
    }
    .tdDatHang .btnDatHang:hover{
        background: #ec971f;
    }
</style>