<link rel="stylesheet" type="text/css" href="/foodanddrink/css/menu.css">
<header id="gtco-header" class="gtco-cover gtco-cover-sm" role="banner" style="background-image: url(/foodanddrink/img/background/anhnen2.jpg)"  style="height: 80px">

    <div class="overlay overlay_edit" style="height: 80px"></div>


</header>

<div class="main">

    <div class="sub-menutrai">
        <ul type="none" class="smenu">
            <li style="padding-left: 15px"><a href="">Best seller <span class="i"><i class=""style="color:#736c6c;margin-left: 103px "></i></span></a>
            </li>
            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=cafe">Caffe<span class="i"><i class="" style="color:#736c6c;margin-left: 70px "></i> </span></a></li>
            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=soda">Soda<span class="i"><i class=""style="color:#736c6c;margin-left: 95px "></i></span></a></li>
            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=sinhto">Sinh tố<span class="i" class="iooi"><i class="fas fa-chevron-right"style="color:#736c6c;margin-left: 179px "><b></b></i></span></a>
<!--                <div class="submenu" >-->
<!--                    <ul >-->
<!--                        <div class="submenu1">-->
<!--                            <ul>-->
<!--                                <li>-->
<!--                                    <a href="">Sinh tố bơ</a>-->
<!--                                    <a href="">Sinh tố mãng cầu</a>-->
<!--                                    <a href="">Sinh tố bơ-mãng cầu</a>-->
<!--                                    <a href="">Sinh tố xoài</a>-->
<!--                                    <a href="">Sinh tố cam</a>-->
<!--                                    <a href="">Sinh tố cam xoài</a>-->
<!--                                    <a href="">Sinh tố dưa hấu </a>-->
<!--                                    <a href="">Sinh tố chanh leo</a>-->
<!--                                    <a href="">Sinh tố việt quất </a>-->
<!--                                    <a href="">Sinh tố dâu</a>-->
<!--                                    <a href="">Sinh tố dâu dừa</a>-->
<!--                                    <a href="">Sinh tố bơ-xoài</a>-->
<!---->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!---->
<!--                        <div class="submenu1">-->
<!--                            <ul>-->
<!--                                <li>-->
<!--                                    <a href="">Sinh tố dừa</a>-->
<!--                                    <a href="">Sinh tố bơ sữa chua</a>-->
<!--                                    <a href="">Sinh tố mãng cầu sữa chua </a>-->
<!---->
<!--                                    <a href="">Xem tất cả >> </a>-->
<!---->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!--                    </ul>-->
<!--                </div>-->
            </li>
            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=nuocep">Các loại nước ép<span class="i" class="iooi"><i class="fas fa-chevron-right"style="color:#736c6c;margin-left: 111px "><b></b></i></span></a>
<!--                <div class="submenu" style="top: -140px">-->
<!--                    <ul >-->
<!--                        <div class="submenu1">-->
<!--                            <ul>-->
<!--                                <li>-->
<!--                                    <a href="">Nước cam nguyên chất</a>-->
<!--                                    <a href="">Nước ép táo</a>-->
<!--                                    <a href="">Nước ép ổi</a>-->
<!--                                    <a href="">Nước ép chanh</a>-->
<!--                                    <a href="">Nước ép dứa </a>-->
<!--                                    <a href="">Nước ép cà rốt</a>-->
<!--                                    <a href="">Nước ép quất </a>-->
<!--                                    <a href="">Nước ép dưa hấu</a>-->
<!--                                    <a href="">Nước ép bưởi </a>-->
<!--                                    <a href="">Nước ép đào</a>-->
<!--                                    <a href="">Nước ép chanh mật ong </a>-->
<!--                                    <a href="">Nước ép quất mật ong</a>-->
<!---->
<!---->
<!---->
<!---->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!---->
<!--                        <div class="submenu1">-->
<!--                            <ul>-->
<!--                                <li>-->
<!--                                    <a href="">Nước ép cóc </a>-->
<!--                                    <a href="">Nước ép cóc-ổi</a>-->
<!--                                    <a href="">Nước ép chanh leo </a>-->
<!--                                    <a href="">Nước ép cam-dứa </a>-->
<!--                                    <a href="">Nước ép cam-cà rốt </a>-->
<!--                                    <a href="">Xem tất cả >> </a>-->
<!---->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!--                    </ul>-->
<!--                </div>-->
            </li>

            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=tra">Các loại trà<span class="i"><i class="fas fa-chevron-right"style="color:#736c6c;margin-left: 150px "><b></b></i></span></a>
<!--                <div class="submenu" style="top: -174px; height: 542px">-->
<!--                    <ul >-->
<!--                        <div class="submenu1">-->
<!--                            <ul>-->
<!--                                <li>-->
<!---->
<!--                                    <a href=""> Trà chanh nha đam</a>-->
<!--                                    <a href="">Trà chanh trân châu trắng</a>-->
<!--                                    <a href="">Trà quất nha đam</a>-->
<!--                                    <a href="">Trà quất trân châu trắng </a>-->
<!--                                    <a href="">Trà quất sả</a>-->
<!--                                    <a href="">Trà quất mật ong</a>-->
<!--                                    <a href="">Trà đào</a>-->
<!--                                    <a href="">Trà đào cam sả</a>-->
<!--                                    <a href="">Trà bưởi </a>-->
<!--                                    <a href="">Trà vải</a>-->
<!---->
<!---->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!--                        <div class="submenu1">-->
<!--                            <ul>-->
<!--                                <li>-->
<!--                                    <a href="">Hồng trà</a>-->
<!--                                    <a href="">Trà nhài</a>-->
<!--                                    <a href="">Trà ô long</a>-->
<!--                                    <a href="">Trà hoa hồng </a>-->
<!--                                    <a href="">Xem thêm...</a>-->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!---->
<!---->
<!--                    </ul>-->
<!--                </div>-->
            </li>
            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=trasua">Các loại trà sữa<span class="i"><i class="fas fa-chevron-right"style="color:#736c6c;margin-left: 120px "><b></b></i></span></a>
<!--                <div class="submenu" style="top: -207px; height: 542px;">-->
<!--                    <ul >-->
<!--                        <div class="submenu1">-->
<!--                            <ul>-->
<!--                                <li>-->
<!---->
<!--                                    <a href="">Hồng trà sữa</a>-->
<!--                                    <a href="">Ô long sữa</a>-->
<!--                                    <a href="">Trà Nhài sữa </a>-->
<!--                                    <a href="">Trà sữa việt quất</a>-->
<!--                                    <a href="">Trà sữa socola</a>-->
<!--                                    <a href="">Trà sữa bạc hà</a>-->
<!--                                    <a href="">Trà sữa dâu</a>-->
<!--                                    <a href="">Trà sữa vải</a>-->
<!--                                    <a href="">Trà sữa nho </a>-->
<!--                                    <a href="">Trà sữa phúc bồn tử</a>-->
<!--                                    <a href="">Trà sữa đậu đỏ</a>-->
<!--                                    <a href="">Trà swuxa matcha</a>-->
<!--                                    <a href="">Trà xoài kem cheese</a>-->
<!---->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!--                        <div class="submenu1">-->
<!--                            <ul>-->
<!--                                <li>-->
<!---->
<!--                                    <a href="">Trà sữa tam đảo</a>-->
<!--                                    <a href="">Trà sữa tổ ong</a>-->
<!--                                    <a href="">Trà sữa hạt dẻ </a>-->
<!--                                    <a href="">Trà sữa caffe</a>-->
<!--                                    <a href="">Trà sữa hokkaido</a>-->
<!--                                    <a href="">Trà sữa pudding</a>-->
<!---->
<!--                                    <a href="" style="color: green">Xem tất cả  >></a>-->
<!---->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!---->
<!--                    </ul>-->
<!--                </div>-->
            </li>
            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=ice-cream">Ice-cream<span class="i"><i class="fas fa-chevron-right"style="color:#736c6c;margin-left: 159px "><b></b></i></span></a>
<!--                <div class="submenu" style="top: -240px">-->
<!--                    <ul >-->
<!--                        <div class="submenu1">-->
<!--                            <ul>-->
<!--                                <li>-->
<!---->
<!--                                    <a href="">Choccolate</a>-->
<!--                                    <a href="">Matcha</a>-->
<!--                                    <a href="">Mint chocolate</a>-->
<!--                                    <a href="">Mint cookie</a>-->
<!--                                    <a href="">Matcha việt quất</a>-->
<!--                                    <a href="">Matcha dâu</a>-->
<!--                                    <a href="">Matcha bạc hà</a>-->
<!--                                    <a href="">Mocha</a>-->
<!--                                    <a href="">Popcon</a>-->
<!--                                    <a href="">Tỉramisu</a>-->
<!--                                    <a href="">Cookie dâu</a>-->
<!--                                    <a href="">Cookie việt quất</a>-->
<!--                                    <a href="">Cookie chocolate</a>-->
<!---->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!--                        <div class="submenu1">-->
<!--                            <ul>-->
<!--                                <li>-->
<!---->
<!--                                    <a href=""> Caffe cốt dừa tuyết </a>-->
<!--                                    <a href=""> Cốt dừa xoài tuyết</a>-->
<!--                                    <a href=""> Cốt dừa cốm xanh</a>-->
<!--                                    <a href=""> Chocolate cốt dừa tuyết</a>-->
<!--                                    <a href="">Chanh leo cốt dừa tuyết</a>-->
<!--                                    <a href="">Chanh tuyết</a>-->
<!--                                    <a href="">Chanh leo tuyết</a>-->
<!---->
<!--                                    <a href=""></a>-->
<!--                                    <a href=""></a>-->
<!--                                    <a href=""></a>-->
<!--                                    <a href=""></a>-->
<!---->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!---->
<!--                    </ul>-->
<!--                </div>-->
            </li>
            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=mocktail">mocktail<span class="i"><i class=""style="color:#736c6c;margin-left: 0px "></i></span></a>
                <div class="submenu" style="top: -273px">

                </div>
            </li>
            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=suachuamix">Sữa chua mix<span class="i"><i class="fas fa-chevron-right"style="color:#736c6c;margin-left: 133px "><b></b></i></span></a>
<!--                <div class="submenu" style="top: -307px;height:1030px">-->
<!--                    <ul >-->
<!--                        <div class="submenu1">-->
<!--                            <ul>-->
<!--                                <li>-->
<!---->
<!--                                    <a href="">Sữa chua hộp</a>-->
<!--                                    <a href="">Sữa chua đá xay caffe</a>-->
<!--                                    <a href="">Sữa chua đá xay việt quất</a>-->
<!--                                    <a href="">Sữa chua đá xay vị xoài</a>-->
<!--                                    <a href="">Sữa chua đá xay vị dâu</a>-->
<!--                                    <a href="">Sữa chua đá xay vị đào</a>-->
<!--                                    <a href="">Sữa chua đá xay bạc hà</a>-->
<!--                                    <a href="">Sữa chua đá xay socola</a>-->
<!--                                    <a href="">Sữa chua lắc vị xoài</a>-->
<!--                                    <a href="">Sữa chua lắc vị việt quất</a>-->
<!--                                    <a href="">Sữa chua lắc vị dâu</a>-->
<!--                                    <a href="">Sữa chua lắc vị đào</a>-->
<!--                                    <a href="">Sữa chua lắc vị caffe</a>-->
<!---->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!--                        <div class="submenu1">-->
<!--                            <ul>-->
<!--                                <li>-->
<!---->
<!--                                    <a href=""> Sữa chua dẻo chanh leo </a>-->
<!--                                    <a href=""> Sữa chua dẻo việt quất</a>-->
<!--                                    <a href=""> Sữa chua dẻo trà xanh</a>-->
<!--                                    <a href=""> Sữa chua dẻo socola</a>-->
<!--                                    <a href=""> Sũa chua dẻo dâu</a>-->
<!--                                    <a href=""> Sũa chua thạch</a>-->
<!--                                    <a href="">Sữa chua hoa quả dầm</a>-->
<!--                                    <a href=""> Sữa chua trân châu</a>-->
<!---->
<!--                                    <a href=""></a>-->
<!--                                    <a href=""></a>-->
<!--                                    <a href=""></a>-->
<!--                                    <a href=""></a>-->
<!---->
<!--                                </li>-->
<!--                            </ul>-->
<!--                        </div>-->
<!---->
<!--                    </ul>-->
<!--                </div>-->
            </li>
            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=kem">Các loại kem<span class="i"><i class=""style="color:#736c6c;margin-left: 23px "></i></span></a>
                <div class="submenu" style="top: -174px">

                </div>
            </li>
            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=bia">Các loại bia<span class="i"><i class=""style="color:#736c6c;margin-left: 25px "></i></span></a>
                <div class="submenu" style="top: -174px">

                </div>
            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=nuocngot">Các loại nước ngọt<span class="i"><i class=""style="color:#736c6c; margin-left: 30px; "></i></span></a></li>
            </li>
            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=banhngot">Các loại bánh ngọt<span class="i"><i class=""style="color:#736c6c;margin-left: 65px "></i></span></a>
                <div class="submenu" style="top: -174px">

                </div>
            </li>
            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=doanvat">Đồ ăn vặt <span class="i"><i class=""style="color:#736c6c;margin-left: 47px "></i></span></a>

            </li>

            <li style="padding-left: 15px"><a href="http://localhost/foodanddrink/menu?phanloai=hoaqua">Đĩa hoa quả<span class="i"></span></a></li>

        </ul>
    </div>
    <!-- //slide -->
    <div class="hinhanh">
        <div class="hinhtrai">
            <div >
                <div class="slideshow-container">

                    <div class="mySlides fade">
                        <img src="/foodanddrink/img/slide/slide1.jpg" style="width:1060px;  height:525px">

                    </div>

                    <div class="mySlides fade">
                        <img src="/foodanddrink/img/slide/slide2.jpg" style="width:1060px;  height:525px">
                        <!-- <div class="text">Nội dung caption của slide thứ 2!</div> -->
                    </div>

                    <div class="mySlides fade">
                        <img src="/foodanddrink/img/slide/slide3.jpg" style="width:1060px;  height:525px">
                        <!-- <div class="text">Nội dung caption của slide thứ 3!</div> -->
                    </div>


                </div>
            </div>


        </div>
    </div>
    <!-- slide -->
</div>
<br>

<div style="text-align:center">
    <span class="dot" onclick="currentSlide(0)"></span>
    <span class="dot" onclick="currentSlide(1)"></span>
    <span class="dot" onclick="currentSlide(2)"></span>
</div>

<div class="gtco-section">
    <div class="gtco-container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center gtco-heading">
                <h2 class="cursive-font primary-color">Popular Dishes</h2>
                <p>Dignissimos asperiores vitae velit veniam totam fuga molestias accusamus alias autem provident. Odit ab aliquam dolor eius.</p>
            </div>
        </div>
        <?php echo $this->getContent(); ?>
    </div>
</div>

<?php echo \Phalcon\Tag::javascriptInclude("js/jquery-3.4.1.min.js"); ?>
<!--<script>-->
<!--    $(document).ready(function () {-->
<!---->
<!--        $(".btnmua").click(function () {-->
<!--            // alert("ok");-->
<!--            var parent =$(this).parents('.col-sm-6');-->
<!--            var maSP = parent.find('input').val();-->
<!--            var src = parent.find('img').attr('src');-->
<!--            $.get("http://localhost/foodanddrink/users/addSP",{maSP:maSP},function (data) {-->
<!--                var sl = $(document).find('.slsp').html(data);-->
<!--            })-->
<!--            alert(maSP);-->
<!--        })-->
<!--    });-->
<!--</script>-->